python_sources(
    name="taplo_fmt",
    resolve="pants-plugins",
    sources=["__init__.py", "taplo_fmt.py", "toml_sources.py"],
)

python_source(
    name="plugin_registry",
    resolve="pants-plugins",
    source="register.py",
)

pants_requirements(name="pants", resolve="pants-plugins")
